# syntax=docker/dockerfile:1.4

FROM ubuntu:22.04 as build
RUN <<EOF
set -eux
apt-get update -y
apt-get install -y --no-install-recommends \
    unzip
rm -rf /var/lib/apt/lists/*
EOF
ADD ./dist/virt-fw-vars.zip /tmp/
WORKDIR /app
RUN unzip /tmp/virt-fw-vars.zip

FROM ubuntu:22.04
WORKDIR /app
COPY --from=build /app ./
ENTRYPOINT ["/app/virt-fw-vars"]
