name: Build
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: ./build.sh
      - name: Test
        run: ./test.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            dist/virt-fw-vars.zip
